# Generated by Django 6.0.6 on 2026-06-20 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de Producto')),
                ('tipo', models.IntegerField(choices=[(1, 'Coleccionables'), (2, 'Tecnología Retro')], default=1, verbose_name='Tipo de Producto')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cantidad_productos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad / Stock')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Precio Unitario')),
                ('imagen_url', models.URLField(blank=True, default='[https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=500](https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=500)', max_length=500, null=True, verbose_name='Enlace de Imagen')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['cod_producto'],
            },
        ),
    ]
