# Generated by Django 6.0.6 on 2026-06-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='productos/default.jpg', null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
    ]
